export type OpportunitiesResponse = {
  age: number;
  chancesToPay: number;
  city: string;
  codeOpportunity: string;
  dataEstimadaPrimeiraParcela: string;
  hasPropertyGuarantee: boolean;
  hasRepurchase: boolean;
  hasWarranty: boolean;
  idOpportunity: number;
  income: number;
  loanReason: string;
  pdAssociada: number;
  prazo: number;
  propertyGuarantee: string;
  qtdCotasDisponiveis: number;
  qtdCotasInvestidas: number;
  qtdTotalCotas: number;
  rating: string;
  ratingCor: string;
  ratingClassificacao: string;
  scholarity: string;
  state: string;
  taxaNominalEmprestimo: number;
  taxaReceberAa: number;
  taxaReceberAm: number;
  taxaRentabilidadeAa: number;
  taxaRentabilidadeAm: number;
  taxaRetornoCDI: number;
  valorCota: number;
  valorCotaRentabilizada: number;
  valorTotalACaptar: number;
  warranty: string;
  isPJ: boolean;
  chancesNotPay: number;
  name?: string;
  operationMarket?: string;
  annualBilling?: number;
  pagamentoUnico: number;
  prazoEmDias: number;
  distributeGracePeriodInterest: 0 | 1 | 2;
  paymentType: 'pagamentos_mensais' | 'pagamento_unico' | 'juros_mensais' | 'pos_juros_mensais_cdi';
  urlImovel?: string;
  urlProduto?: string;
  recommend: boolean;
  spe: 0 | 1;
  paymentTypeDescription: string;
  cashback: number;
  hasCashback: boolean;
  annualReceiveRate: number;
  termInDays: number;
  urlLogo?: string;
  novaOportunidade: boolean;
  qtdOportunidadesTomador: number;
}[];
