export type CompleteRequest = {
  cpf?: string;
  profession?: string;
  nationality?: string;
  birthCity?: string;
  isPep?: 0 | 1;
  gender?: string;
  dateOfBirth?: Date;
  maritalStatus?: string;
  spouse?: string;
  isUnitedStatesResident?: 0 | 1;
  street?: string;
  streetNumber?: string;
  complement?: string;
  neighborhood?: string;
  postalCode?: string;
  city?: string;
  state?: string;
  country?: string;
  bank?: string;
  bankNumber?: string;
  accountType?: string;
  agency?: string;
  accountNumber?: string;
  accountDigit?: string;
  cellphone?: string;
  email?: string;
  hasOwnResidence?: 0 | 1;
  scholarity?: string;
};
