export type InvestimentsResponse = {
  ccbView: null | string;
  codeOpportunity: string;
  hasPropertyGuarantee: boolean;
  hasRepurchase: boolean;
  hasWarranty: boolean;
  idAppliedInvestment: number;
  idOpportunity: number;
  idProposal: number;
  idStatus: number;
  idUserBorrower: number;
  nameBorrower: string;
  cityBorrower: string;
  stateBorrower: string;
  isPj: boolean;
  operationMarket: string;
  prazo: number;
  propertyGuarantee: null | string;
  qtdCotasInvestidas: number;
  qtdParcelasPagas: number;
  rating: string;
  ratingCor: string;
  ratingClassificacao: string;
  valorLucroBrutoEsperado: number;
  valorTotalInvestido: number;
  valorTotalReceber: number;
  valorTotalRecebido: number;
  warranty: null | string;
  dataCompra: string;
  isRenegotiation: boolean;
  isMova: boolean;
  logoBorrower: string;
  paymentType: string;
  proximoRecebimento: string;
}[];
